quantcast/qfs

webui/qfsstatus.py

Related to #69 when I set `chunkServer.hostname` to a dns name, the metaserver and chunkserver communication works, but the webui is broken (returning 504 errors).
The problem is [here](https://github.com/quantcast/qfs/blob/master/webui/qfsstatus.py#L795). It expects two IP addresses but it has two dns names. I'm doing a dns lookup now when instantiating the class.
The error:
```
File "qfsstatus.py", line 1177, in ping
status.upServers.sort()
File "qfsstatus.py", line 799, in __cmp__
return cmp(socket.inet_aton(self.host), socket.inet_aton(other.host))
error: illegal IP address string passed to inet_aton
```

Web ui: Fix when chunk advertised hostname is a domain

---

.travis.yml

Added continuous integration support for Centos (6). Both Ubuntu (14.04) and Centos (6) are now built by using Docker in Travis-CI.

Travis-CI Centos6 build support

---

.appveyor.yml

we can only cache up to 500 mb on appveyor and our build directory is near 2 gb

appveyor: remove caching the build directory

---

cmake/Modules/Findgtest.cmake

In some machines, file extension (.zip) of downloaded gtest file gets stripped away which causes the proceeding commands to fail. This change makes sure that filename of gtest package stays the same after it's downloaded.

use a more robust wget command to download gtest dependency

---

.ratignore
CMakeLists.txt
Makefile
scripts/rat.sh

This change adds a new make target, rat, which allows users to check files
within the qfs source tree for missing license information. The file .ratignore
is used as a list of regular expressions for files which should be ignored.

rat: check specific files for license information

---

src/cc/access/qfs_access_jni.cc
src/java/hadoop-qfs/src/main/java/com/quantcast/qfs/hadoop/IFSImpl.java
src/java/hadoop-qfs/src/main/java/com/quantcast/qfs/hadoop/QFSImpl.java
src/java/hadoop-qfs/src/main/java/com/quantcast/qfs/hadoop/QFSOutputStream.java
src/java/hadoop-qfs/src/main/java/com/quantcast/qfs/hadoop/QuantcastFileSystem.java
src/java/hadoop-qfs/src/test/java/com/quantcast/qfs/hadoop/QFSEmulationImpl.java
src/java/qfs-access/src/main/java/com/quantcast/qfs/access/KfsAccess.java
src/java/qfs-access/src/main/java/com/quantcast/qfs/access/KfsTest.java

Currently, KfsAccess java library uses the default values for create parameters such as number of stripes, number of recovery stripes, stripe size... This change lets the user pass a string value that specifies create parameters for a new file.

add API support to pass create parameters for new files

---

README.md

In line "$ echo 'Hello World' | cptoqfs -s localhost -p 20000 -S -r 1 -k /qfs/tmp/helloworld -d -", -S already implies "use 1 replica".

Remove -r argument from cptoqfs example in README.md.

---

src/cc/libclient/Monitor.cc

This makes the client monitor less chatty.

make qfs client monitor print information only when there is a change.

---

src/cc/tools/qfsfileenum_main.cc

Also, it removes "-f <path>" option to avoid confusions.

display more details in qfsfileenum help menu [QFS-289]

---

src/cc/libclient/KfsClient.cc

This change makes sure that provided qfs client monitor plugin path is not empty.

check client monitor plugin path length

---

examples/sampleservers/sample_setup.py

chunkServer.diskIo.crashOnError and chunkServer.abortOnChecksumMismatchFlag are not crucial for sample_setup script, which is used to install/uninstall an local QFS instance with minimum effort. Removing them from the script will make the generated configuration files more concise.

remove unneeded chunkserver parameters from sample_setup script

---

src/java/qfs-access/src/main/java/com/quantcast/qfs/access/KfsAccess.java

If the kfsaccess native code fails to load, the current reaction is to dump a stacktrace and call System.exit.
This is rather unfriendly and can make it hard to diagnose the issue in situations where syserr output is not easily available. It also prevents any attempt to probe for qfs availability.
This code will now throw an exception instead.
@mikeov  @mckurt

QFS-325 Throw exception if native code load fails instead of calling exit

---

travis/script.sh

Apple has stopped to ship the openssl headers by itself. This change passes the required header to cmake to fix the Travis-CI build on OSX.

Travis: pass OPENSSL_ROOT_DIR header to cmake to fix build on OSX

---

src/java/hadoop-qfs/src/main/java/com/quantcast/qfs/hadoop/IFSImpl.java
src/java/hadoop-qfs/src/main/java/com/quantcast/qfs/hadoop/QFSImpl.java
src/java/hadoop-qfs/src/main/java/com/quantcast/qfs/hadoop/QuantcastFileSystem.java
src/java/hadoop-qfs/src/test/java/com/quantcast/qfs/hadoop/QFSEmulationImpl.java

This change makes a QuantcastFileSystem instance fetch the standard Hadoop umask value from the Configuration used when the instance is created then sets that umask value in its client.
This will improve general Hadoop compatibility.
It also eliminates a problem with Spark and Hive when QFS is set as the default filesystem.
Hive needs to create a /tmp/hive directory with a permission of 777 so it can create user-specific subdirectories. It creates a new instance of the default filesystem with the standard Hadoop umask property set to 000, tries to create the /tmp/hive directory, then checks that the directory had the correct permissions.
Before this change, QuantcatFileSystem was ignoring the umask property and Hive would complain that that /tmp/hive was not world-writable.  With this …

QFS-332 - make QuantcastFileSystem honor umask setting from jobconf for better Hadoop/Hive compatility

---

Makefile

Spark is bundling with Hadoop 2.7.2.
Added a build of the java hadoop shim for 2.7.2
@mikeov @mckurt

Add build for Hadoop 2.7.2

---

src/cc/tests/integtest.cc
travis/script.sh

This PR fixes a couple of issues with Travis-CI builds.
1) Google test metaserver and chunkserver environments used to set the default build directory to "debug". Change it to "release".
2) The base travis centos7 image doesn't have "which" binary installed. Add "which" as a dependency.
3) Centos7 has the distro information in /etc/redhat-release, instead of /etc/issue which is used by Makefile to name the QFS tarball. Write correct distro information to /etc/issue before building QFS.
@kstinsonqc

fix travis-ci centos7 build issues

---

src/java/hadoop-qfs-2/src/main/java/com/quantcast/qfs/hadoop/Qfs.java
src/java/hadoop-qfs/src/main/java/com/quantcast/qfs/hadoop/QuantcastFileSystem.java

The Hadoop shim for QFS was not checking that that fully qualified path arguments were for the correct FileSystem instance.
For example,
URI uri = URI.create("qfs://ms1.example.com:10000");
FileSystem fs = FileSystem.get(uri, new Configuration());
FileStatus[] otherQFSList = fs.listStatus(new Path("qfs://ms2.example.com:20000/"));
FileStatus[] otherQFSList = fs.listStatus(new Path("hdfs://127.0.0.1:20000/"));
will return a listing of the root of the filesystem at ms1.example.com:10000 in both cases
This can cause confusion, especially in contexts when the association between filesystems objects and paths may be a bit more obscure. Some Spark users have been thrown by this behavior.
The base FileSystem class provides a checkPath(Path) method to check that if a path is fully qualified, then …

Hadoop shim: added calls to checkPath to check fully-qualified path inputs are for the correct filesystem

---

conf/MetaServer.prp

metaDataSync.servers variable should contain a list of IP
addresses and ports of metaservers that should be used for
initial synchronization. Existing comments doesn't contain
this information.

Clarified comments about metaDataSync.servers var

---

src/cc/common/BufferedLogWriter.cc
src/cc/common/StBuffer.h
src/cc/meta/LayoutManager.cc

* `StBuffer::Swap(StBufferT& inBuf)` cannot take const argument
* `MessageStream::xsputn` memcpys at least 0 bytes
* `LayoutManager::CSWriteExtra::Write()` handles bool

Fix errors and warnings from GCC 7.2

---

src/java/pom.xml

Related to spring-guides/gs-maven#21

Specify source and target to avoid build error

---

webui/qfsstatus.py

Add /query/meta endpoint to webui which returns a json version of the status.
Parse rebalanceStatus and watchdog stats in webui.
Json status makes it easy for scripts to query the status of qfs.
Example response from http://localhost:22000/query/meta
```
{
"evacuatingServers": [],
"freeFsSpace": 183537364992,
"serversByRack": {},
"retiringServers": [],
"config": {
"metaServer.chunkServerPort": "20100",
"metaServer.clientPort": "20000",
"metaServer.clientThreadCount": "4",
"metaServer.clusterKey": "myTestCluster",
"metaServer.cpDir": "/Users/ktsukida/qfsbase/meta/checkpoints",
"metaServer.log.logDir": "/Users/ktsukida/qfsbase/meta/logs",
"metaServer.logDir": "/Users/ktsukida/qfsbase/meta/logs",
"metaServer.minChunkservers": "1",
"metaServer.msgLogWriter.logLevel": "DEBUG", …
```

webUI: add /query/meta endpoint and parse watchdog and vrStatus

---

src/go/README.md
src/go/error.go
src/go/file.go
src/go/file_test.go
src/go/fileinfo.go
src/go/fileinfo_test.go
src/go/go.mod
src/go/go.sum
src/go/qfs.go
src/go/qfs_test.go

This adds Go bindings for the QFS C API.  It implements some of the available functions, specifically those which have been used for internal services within Quantcast.  There are definitely some missing, but this library may definitely be useful to others even in it's current form.
All the code has been previously reviewed and approved inside Quantcast ([OPENSOURCE-95](https://bugs.corp.qc/browse/OPENSOURCE-95)). I'm removing the Git history to reduce the change of exposing confidential information, but this library was implemented by the following people:
* Steve Day
* Eric Culp
* Noah Goldman
This is currently being used in production at Quantcast.
@kstinsonqc @mckurt

Add Go bindings
